import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { adminModerationApi, ApiError, apiFetch } from "./api/client";

type Report = { id: string; targetType: string; targetId: string; reason: string; detail: string | null; status: string; createdAt: string };
export default function AdminReportsPage() {
  const navigate = useNavigate(); const { reportId } = useParams(); const [items, setItems] = useState<Report[]>([]); const [detail, setDetail] = useState<Report | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const path = reportId ? `/api/admin/reports/${reportId}` : "/api/admin/reports"; apiFetch<Report | Report[]>(path).then((result) => reportId ? setDetail(result as Report) : setItems(result as Report[])).catch((e: unknown) => { if (e instanceof ApiError && [401, 403].includes(e.status)) navigate("/", { replace: true }); else setError("신고 정보를 불러오지 못했습니다."); }); }, [navigate, reportId]);
  const content = detail ? [detail] : items;
  async function act(item: Report, status: "REVIEWED" | "REJECTED") { try { const updated = await adminModerationApi.reviewReport(item.id, status); const next = { ...item, status: (updated as Report).status ?? status }; setDetail(next); setItems((current) => current.map((candidate) => candidate.id === item.id ? next : candidate)); } catch (e) { setError(e instanceof ApiError ? "신고 상태를 변경하지 못했습니다." : "처리 중 오류가 발생했습니다."); } }
  async function hide(item: Report) { if (item.targetType !== "PUBLICATION") return; try { await adminModerationApi.setPublicationVisibility(item.targetId, false, `신고 ${item.id} 검토 결과`); setError("게시글을 숨겼습니다."); } catch { setError("게시글을 숨기지 못했습니다."); } }
  return <main className="page notification-page"><section className="localcare-hero"><p className="eyebrow">MODERATION</p><h1>{detail ? "신고 상세" : "신고 큐"}</h1><p>운영자가 접수된 신고를 검토합니다.</p></section>{error ? <p role="alert">{error}</p> : null}<section className="notification-list">{content.map((item) => <article className="surface-card notification-item" key={item.id}><Link to={`/admin/reports/${item.id}`}><span className="publication-chip">{item.reason}</span><h2>{item.targetType} · {item.targetId}</h2><p>{item.detail ?? "상세 설명 없음"}</p><small>{new Date(item.createdAt).toLocaleString("ko-KR")} · {item.status}</small></Link>{detail && item.status === "OPEN" ? <div className="profile-actions"><button className="button button-primary" type="button" onClick={() => void act(item, "REVIEWED")}>검토 완료</button><button className="button button-soft" type="button" onClick={() => void act(item, "REJECTED")}>기각</button>{item.targetType === "PUBLICATION" ? <button className="button button-danger" type="button" onClick={() => void hide(item)}>게시글 숨김</button> : null}</div> : null}</article>)}</section><Link className="publication-text-link" to={detail ? "/admin/reports" : "/"}>{detail ? "신고 큐로" : "홈으로"}</Link></main>;
}
