ALTER TABLE member_profile
    ADD COLUMN IF NOT EXISTS show_public_posts BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_public_comments BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_public_pets BOOLEAN NOT NULL DEFAULT TRUE;
